services:
  wrapper:
    container_name: wrapper
    image: chaslllll/wrapper-test:latest
    network_mode: bridge
    ports:
      #- "10020:10020"
      #- "20020:20020"
      - "7681:7681"
    volumes:
      - ./data:/app/rootfs/data               #wrapper需要的rootfs目录，2FA也在此目录，默认不需改动；
      - ./amdl/config.yaml:/app/config.yaml   #amdl的config文件，运行时不需改动路径，后续修改config修改此处即可；
      - /mnt/disk1:/mnt/disk1                 #映射需要保持音乐的目录，后半段与config.yaml中一致，不需改动，只需改前面路径
    restart: unless-stopped
