name: Build and Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - start.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: git_wrapper
      run: |
        echo "当前工作目录: $(pwd)"
        wget "https://github.com/zhaarey/wrapper/releases/download/linux.V2/wrapper.x86_64.tar.gz"
        mkdir ${GITHUB_WORKSPACE}/wrapper
        tar -xzf wrapper.x86_64.tar.gz -C ${GITHUB_WORKSPACE}/wrapper
        ls -l ${GITHUB_WORKSPACE}/  

    - name: git_amdl
      run: |
        echo "当前工作目录: $(pwd)"
        git clone https://github.com/zhaarey/apple-music-downloader.git
        apt update && apt install golang -y
        cd apple-music-downloader
        go build -o dl main.go
        mv dl ../
        mv config.yaml ../
        ls -l ../

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current date
      run: |
        export TZ='Asia/Shanghai'
        echo "BUILD_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Build and push Docker image to GitHub Packages
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/wrapper-amdl:latest
          ghcr.io/${{ github.repository_owner }}/wrapper-amdl:${{ env.BUILD_DATE }}
